[package]
build = "build.rs"
name = "rspm"

authors.workspace = true
categories.workspace = true
description.workspace = true
edition.workspace = true
homepage.workspace = true
keywords.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[lib]
path = "lib.rs"

[package.metadata.docs.rs]
all-features = false
features = ["full"]
rustc-args = ["--cfg", "docsrs"]
version = "v"

[package.metadata.release]
no-dev-version = true
tag-name = "v"

[dependencies]
rspm-core = { default-features = false, workspace = true }

[dev-dependencies]
criterion = { features = ["plotters"], workspace = true }
lazy_static = { workspace = true }

[features]
default = [
  "std",
]

full = [
  "default",
  "hashbrown",
  "json",
  "time",
]

# ********* [FF] Flags *********

time = [
  "std",
  "chrono",
  "time_03",
  "rspm-core/time",
]

# ********* [FF] Targets *********
nightly = [
  "rspm-core/nightly",
]

wasi = [
  "rspm-core/wasi",
]

wasm = [
  "alloc",
  "wasm_bindgen",
  "rspm-core/wasm",
]

# ********* [FF] Standard Library *********
alloc = [
  "rspm-core/alloc",
]

std = [
  "alloc",
  "rspm-core/std",
]

# ********* [FF] Deps *********
chrono = [
  "rspm-core/chrono",
]

json = [
  "rspm-core/json",
]

rayon = [
  "rspm-core/rayon",
]

serde = [
  "rspm-core/serde",
]

serde_json = [
  "rspm-core/serde_json",
]

time_03 = [
  "rspm-core/time_03",
]

tracing = [
  "rspm-core/tracing",
]

wasm_bindgen = [
  "rspm-core/wasm_bindgen",
]

witbind = [
  "rspm-core/witbind",
]

# ************* [Benchmarks] *************
[[bench]]
harness = false
name = "default"
required-features = ["std"]

# ************* [Unit Tests] *************
[[test]]
name = "default"
required-features = []
